create table ETPORD.ETP_ORDER_SELL
(
    ORDER_ID         NUMBER,
    FIRM_SERIAL_ID   NUMBER,
    SEC_SERIAL_ID    NUMBER,
    ORDER_STATUS     VARCHAR2(3),
    INSERT_DATE      DATE,
    MODIFIED_DATE    DATE,
    ORDER_TYPE       VARCHAR2(1),
    PRICE            NUMBER,
    ORG_QNTY         NUMBER,
    REM_QNTY         NUMBER,
    NIN              NUMBER(10),
    TRADER_SERIAL_ID NUMBER,
    BOOK_KEEPER      VARCHAR2(4),
    CLEAN_PRICE      NUMBER,
    CURRENT_YIELD    NUMBER,
    GROSS_PRICE      NUMBER,
    YTM              NUMBER,
    ACCRUED_INTEREST NUMBER,
    SETTLEMENT_VALUE NUMBER,
    DAYS_TO_MATURITY NUMBER,
    REC_SEQ          NUMBER,
    IS_DUAL          VARCHAR2(1) default 'N',
    DUAL_SEQ         NUMBER      default 0,
    FIRM_ORDER_ID    VARCHAR2(50)
)
/

create index ETPORD.SELL_SEC_SER_INDX
    on ETPORD.ETP_ORDER_SELL (SEC_SERIAL_ID)
/

create unique index ETPORD.SELL_ORDID_INDX
    on ETPORD.ETP_ORDER_SELL (ORDER_ID)
/

create index ETPORD.SELL_INDX
    on ETPORD.ETP_ORDER_SELL (SEC_SERIAL_ID, PRICE, CLEAN_PRICE, NIN)
/

create index ETPORD.SELL_INDX_OUT
    on ETPORD.ETP_ORDER_SELL (TRUNC("INSERT_DATE"), ORDER_STATUS, REM_QNTY)
/

